#!/bin/sh
OPTS=""

if [ -n "$D" ]; then
    OPTS="--root=$D"
fi

if type systemctl >/dev/null 2>/dev/null; then
	systemctl $OPTS enable gplv3-notice.service

	if [ -z "$D" -a "enable" = "enable" ]; then
		systemctl --no-block restart gplv3-notice.service
	fi
fi
# Begin section update-rc.d
if type update-rc.d >/dev/null 2>/dev/null; then
	if [ -n "$D" ]; then
		OPT="-r $D"
	else
		OPT="-s"
	fi
	update-rc.d $OPT gplv3-notice defaults 99
fi
# End section update-rc.d
