#!/bin/sh
# Begin section update-alternatives
update-alternatives --install /lib/firmware/am57xx-pru1_0-fw am57xx-pru1_0-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt1_0.out 100
update-alternatives --install /lib/firmware/am57xx-pru1_1-fw am57xx-pru1_1-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt1_1.out 100
update-alternatives --install /lib/firmware/am57xx-pru2_0-fw am57xx-pru2_0-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt2_0.out 100
update-alternatives --install /lib/firmware/am57xx-pru2_1-fw am57xx-pru2_1-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt2_1.out 100
# End section update-alternatives
