#!/bin/sh
# Begin section update-alternatives
update-alternatives --remove  am57xx-pru1_0-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt1_0.out
update-alternatives --remove  am57xx-pru1_1-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt1_1.out
update-alternatives --remove  am57xx-pru2_0-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt2_0.out
update-alternatives --remove  am57xx-pru2_1-fw /lib/firmware/pru/PRU_RPMsg_Echo_Interrupt2_1.out
# End section update-alternatives
